package org.peanut.generation.collection;

import java.util.Collection;
import java.util.function.Supplier;

public interface CollectionGenerator<C extends Collection<?>>
{
	/**
	 * Returns a new {@link Collection} of the default size populated with
	 * values generated according to a {@link Supplier}.
	 * 
	 * @param <V>
	 * @param <C>
	 * 
	 * @param generationSupplier
	 *            The {@link Supplier} that will be used to generate the
	 *            contents of the {@link Collection}.
	 * @return A new {@link Collection} of a default size, filled with values
	 *         generated by a {@link Supplier}.
	 */
	public <V> C generateContents(Supplier<V> generationSupplier);

	/**
	 * Returns a new {@link Collection} of a specified size populated with
	 * values generated according to a {@link Supplier}.
	 * 
	 * @param <V>
	 * 
	 * @param generationSupplier
	 *            The {@link Supplier} that will be used to generate the
	 *            contents of the {@link Collection}.
	 * @param size
	 *            The initial size of the {@link Collection}.
	 * @return A new {@link Collection} of a default size, filled with values
	 *         generated by a {@link Supplier}.
	 */
	public <V> C generateContents(Supplier<V> generationSupplier, int size);
}
